[project]
name = "openfilenet"
version = "0.1.1"
description = "OpenFilenet is a lightweight, zero-config peer-to-peer file sharing library designed to abstract away file sharing across code runtimes."
readme = { file = "pip-readme.md", content-type = "text/markdown" }
authors = [
    { name = "Vamsi Karnam", email = "saivamsi.karnam@gmail.com" }
]
license = { file = "LICENSE" }
requires-python = ">=3.8"

# No hard dependency on cryptography; it's optional (only required if encrypt=True)
dependencies = []

keywords = ["p2p", "lan", "networking", "filesharing", "api", "developer-tools", "file share"]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: System :: Networking",
    "Topic :: System :: Distributed Computing",
    "Topic :: Internet",
    "Topic :: Utilities",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Intended Audience :: Developers"
]

[project.optional-dependencies]
# Install with: pip install "openfilenet[cryptography]"
cryptography = ["cryptography>=42.0.0"]

[project.urls]
Homepage = "https://github.com/vamsi-karnam/openfilenet"
Repository = "https://github.com/vamsi-karnam/openfilenet"
Issues = "https://github.com/vamsi-karnam/openfilenet/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"